apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/devoteamgcloud/dgc-dk-gitops-frontend
    targetRevision: HEAD
    path: ./argo/argo-config
  syncPolicy: 
    automated:
      prune: true