apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/cbrandborg/gitops-online-boutique-demo
    targetRevision: HEAD
    path: ./argo/frontend
  syncPolicy: 
    automated:
      prune: true