apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: frontend-
resources:
- frontend.yaml
- ingress.yaml
images:
- name: europe-west1-docker.pkg.dev/interview-demos/gitops-online-boutique-frontend-demo/frontend-demo
  newTag: "4989702854"
