apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: frontend-
resources:
- frontend.yaml
- ingress.yaml
images:
- name: europe-west1-docker.pkg.dev/prj-dt-eu-gitops-compute/dgc-dk-frontend-online-boutique/frontend-demo
  newTag: "4540805740"
