
name: "docker-build-push"

on: 
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'productcatalogservice/**'

env:
  LOCATION: europe-west1
  PROJECT_ID: interview-demos
  PROJECT_NUM: 1937348260
  ARTIFACT_REGISTRY: gitops-online-boutique-frontend-demo
  IMAGE_NAME: europe-west1-docker.pkg.dev/interview-demos/gitops-online-boutique-frontend-demo/frontend-demo
  SERVICE_ACCOUNT: sa-frontend-CICD@interview-demos.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_POOL: wl-pool-frontend-boutique-gh
  WL_PROVIDER: gitops-demo-github-provider
  APP-VERSION: ${{ github.run_id }}

permissions: write-all

jobs:
  build-push:
    name: Building and pushing to Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - id: "gcloud-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: "projects/${{ env.PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL }}/providers/${{ env.WL_PROVIDER }}"
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - id: "docker-auth"
        name: "Configure docker repo"
        run: |
          gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev

      - id: "docker-build"
        name: "Build image"
        run: |
          docker build ./src --tag ${{ env.IMAGE_NAME }}/frontend-demo:${{ env.APP-VERSION }}
          docker build ./productcatalogservice --tag ${{ env.IMAGE_NAME }}/catalog-service:latest
          

      - id: "docker-push"
        name: "Push image to registry"
        run: |
          docker push ${{ env.IMAGE_NAME }}/frontend-demo:${{ env.APP-VERSION }}
          docker push ${{ env.IMAGE_NAME }}/catalog-service:latest

      - uses: imranismail/setup-kustomize@v2

      - id: "kustomize-update-tag"
        name: "Update image tag using Kustomize"
        run: |

          cd argo/frontend
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ env.APP-VERSION }}
          git add kustomization.yaml
          cd ../..

          git config --local user.email "bump-version-bump@github.com"
          git config --local user.name "github-actions-bump-version"

          git commit -m "Bump version [automated commit]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true